### ISSUE TITLE
Merging efforts?

### ISSUE THREAD

**Issue by Lewiscowles1986** [KinG-InFeT/fs-for-wp-fullstory-com-integration#1]
Hello, Ciao,

I maintain https://github.com/LewisCowles1986/cd2-fullstory-integration which does the same things your plugin does, but has one field for people to be concerned with. I Just updated it today and added some nice features.

We both support filters for site-owners to add their own fields, some form of WooCommerce detection, a settings page, use GPL.

Want to join efforts?

The only thing I'd remove is the donate URL and link to a site with what seems like Warez.

Other than that, I like that you have translations, two interesting options I'd like to know more about.

We could keep the JS snippet and allow for placement in an advanced fields section so that people fall-back to the built-in snippet to avoid headache.

Let me know what you think.

**Comment by KinG-InFeT** [comment]
Hello,
I had already seen the plugin but I wanted something that would allow me not to anutenere the js snippet (which could change often) so I opted for the completion of the fullstory wizard which, at the end of the registration, makes the whole snippet copy for then be able to use it if necessary.
At the moment the plugin is in open source, you can safely make pull requests to the branch to expand its functionality and maybe publish a new version.
